### ISSUE TITLE
Fix the bug raising the error "bad substitution" on zsh

### ISSUE THREAD

**Issue by shahrokh-bahtooei** [Lirt/markdown-toc-bash#7]
When I try to run the bash on zsh, I face with this error:
```
% ./markdown-toc.sh my_markdown.md
## Table of Contents

- ./markdown-toc.sh: line 61: ${LINK,,}: bad substitution

```

**Comment by Lirt** [comment]
Hi @ShahrokhBahtooei,

Line 61 is `LINK=${LINK,,}` and it should lowercase the contents of variable `LINK`. This should not fail in normal case.

Can you try to run this and show me output? Maybe you use newer version of bash or something..

```bash
bash --version
bash markdown-toc.sh my_markdown.md
```

Also if this doesn't help us and your input file is not something you don't want to share, it would help me to troubleshoot if I see the contents.

**Comment by shahrokh-bahtooei** [comment]
```
% bash --version             
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.

```

```
% bash markdown-toc.sh git_commands.md 
## Table of Contents

- markdown-toc.sh: line 62: ${LINK,,}: bad substitution
```
Here's my markdown file:
https://gist.github.com/shahrokh-bahtooei/392e8189670830a550ced99513c70de0

_Commenting out_ the line 62 appears to fix the issue for my file as the links work fine.

**Comment by Lirt** [comment]
Hi @shahrokh-bahtooei,

sorry for missing answer here. The lowercase functionality `${,,}` was added to bash in version 4, so you need newer bash. 

About the `zsh`, this script was not tested with `zsh` and is meant to be used with bash.

I can try to add zsh compatibility later.
