### ISSUE TITLE
Duplicate headings are not handled

### ISSUE THREAD

**Issue by tomodachi94** [Lirt/markdown-toc-bash#9]
Currently, if I have a Markdown file that looks like this:
```md
# Heading Foo
## Heading Bar
# Heading Baz
## Heading Bar
```

The script incorrectly generates this:
```md
- [Heading Foo](#heading-foo)
  - [Heading Bar](#heading-bar)
- [Heading Baz](#add-on-mods)
  - [Heading Bar](#heading-bar)
```

Note that, for the second occurrence of Heading Bar, it would link to the first occurrence of Heading Bar on GitHub.

It should probably look like this (note the changes in the last entry):

```md
- [Heading Foo](#heading-foo)
  - [Heading Bar](#heading-bar)
- [Heading Baz](#add-on-mods)
  - [Heading Bar](#heading-bar-1)
```

**Comment by Lirt** [comment]
Hi @tomodachi94,

Thank you for report, I didn't notice this can happen and is supported. 

I added new commit that fixes this issue along with a test. Feel free to pull and try it. More tests to ensure regressions don't happen will be added later.

Enjoy.

**Comment by tomodachi94** [comment]
Thank you for the fast fix :) I'll give it a try this evening.
